spring:
  application:
    name: spring-cloud-eureka-client-school-service
  main:
    allow-circular-references: true
server:
  port: 9098
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
