spring:
  application:
    name: spring-cloud-eureka-feign-client-student-service
    
server:
  port: 9100
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}